# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .  # Install VuVoPy using pyproject.toml or setup.py
  system_packages: false

sphinx:
  configuration: docs/source/conf.py
